### PR TITLE
Put values from tables in test file

### LINKED ISSUE #17: Combine test values from ISO 2533 into full test file
We need to move the values of the ISO 2533 tables into the test structure (`tests.yml`):
* iso-2533-1975-table5.yaml
* iso-2533-1975-table6.yaml
* iso-2533-1975-table7.yaml

_Originally posted by @ronaldtse in https://github.com/metanorma/atmospheric/issues/15#issuecomment-1933292174_

### PR DESCRIPTION
**Pull request by newbthenewbd**
Fixes #17. Converted with the following Python script:
```python
import re

filenames = ["iso-2533-1975-table5.yaml", "iso-2533-1975-table6.yaml", "iso-2533-1975-table7.yaml"]

inputs = [0 for x in range(len(filenames))]
output = open("tests.yml", "w")

for i, name in enumerate(filenames):
	inputs[i] = open(name, "r")

entries = [{} for x in range(2032)] # count of "  - "

for i in range(len(entries)):
	for f in inputs:
		match = None
		while match is None:
			line = f.readline()
			match = re.search(r'^  (-| ) (.+):(.*)', line)
		while match is not None:
			entries[i][match.group(2)] = match.group(3)
			line = f.readline()
			match = re.search(r'^  (-| ) (.+):(.*)', line)

sortedentries = res_list = {frozenset(item.items()) : 
            item for item in sorted(entries, key = lambda e: int(e["geopotential-altitude"]))}.values()

output.write("---\n")

for e in sortedentries:
	output.write("- H: " + str(float(e["geopotential-altitude"])) + "\n")
	output.write("  h: " + str(float(e["geometrical-altitude"])) + "\n")
	output.write("  TK: " + str(float(e["temperature-K"])/1000) + "\n")
	output.write("  TC: " + str(float(e["temperature-C"])/1000) + "\n")
	output.write("  p_mbar:" + e["p-mbar"] + "\n")
	output.write("  p_mmhg:" + e["p-mmHg"] + "\n")
	output.write("  rho:" + e["density"] + "\n")
	output.write("  g:" + e["acceleration"] + "\n")
	output.write("  p_p_n:" + e["ppn"] + "\n")
	output.write("  rho_rho_n:" + e["rhorhon"] + "\n")
	output.write("  root_rho_rho_n:" + e["sqrt-rhorhon"] + "\n")
	output.write("  a: " + str(float(e["speed-of-sound"])/1000) + "\n")
	output.write("  mu:" + e["dynamic-viscosity"] + "\n")
	output.write("  v:" + e["kinematic-viscosity"] + "\n")
	output.write("  lambda:" + e["thermal-conductivity"] + "\n")
	output.write("  H_p:" + e["pressure-scale-height"] + "\n")
	output.write("  gamma:" + e["specific-weight"] + "\n")
	output.write("  n:" + e["air-number-density"] + "\n")
	output.write("  v_bar:" + e["mean-speed"] + "\n")
	output.write("  omega:" + e["frequency"] + "\n")
	output.write("  l:" + e["mean-free-path"] + "\n")
	output.write("\n")

for f in inputs:
	f.close()

output.close()
```

### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by ronaldtse** [comment]
@newbthenewbd you can also commit the python script so you don't need to paste it in the description 😉

**Comment by newbthenewbd** [comment]
It's a different one every time :-) Doesn't it then end in someone's ruby gems?

Edit: as in to mean, I just create them for ad-hoc purposes, but if you find them useful :)

**Comment by newbthenewbd** [comment]
Anyways, hold on with this, I guess, for what's going on over at #19...

**Comment by newbthenewbd** [comment]
Since, if we're only using rows-H, might as well force push that variant to the PR :) Do we, @ronaldtse?

**Comment by ronaldtse** [comment]
> Since, if we're only using rows-H, might as well force push that variant to the PR :) Do we, @ronaldtse?

Later on we have to also create tables that use lookup with "small h" (geometric altitude), so we should add those methods.

Table 5
Screenshot 2024-02-09 at 10 47 23 AM

Screenshot 2024-02-09 at 10 47 33 AM

Table 6
Screenshot 2024-02-09 at 10 48 07 AM

Screenshot 2024-02-09 at 10 48 37 AM

Table 7
Screenshot 2024-02-09 at 10 49 39 AM
Screenshot 2024-02-09 at 10 50 04 AM

**Comment by newbthenewbd** [comment]
Hmm, so something like two separate test files? That can be done :)

**Comment by ronaldtse** [comment]
@newbthenewbd sounds like a reasonable idea?

**Comment by ronaldtse** [comment]
You might prefer to use a YAML library to write out the values?

**Comment by newbthenewbd** [comment]
Well sure, that's why the scripts are ad-hoc :-) Do we need better-made ones?

**Comment by newbthenewbd** [comment]
Like, I'd kind of been spending the better mental on trying to think up why the remaining tests fail, realize this is horrendous... :)

**Comment by ronaldtse** [comment]
Any broad categories of failures do you see? 

> Well sure, that's why the scripts are ad-hoc :-) Do we need better-made ones?

This is fine… it’s a one time processing.

The goal is really to regenerate the tables through code.

**Comment by newbthenewbd** [comment]
> Any broad categories of failures do you see?

Too imprecise computation, bad assumptions about the test data (like what I am working on right now, adding support for rounding to significant digits), algorithmic errors (increasingly getting fixed, I don't see one at this time)...

**Comment by newbthenewbd** [comment]
And another funny category, these missing p_mmhg values :)
image

**Comment by newbthenewbd** [comment]
I think/hope that with the commit above, only:
* the above-mentioned missing p_mmhg values,
* bad data in tables,
* precision of computation (e.g. too imprecise coefficient values)

failures should remain...

**Comment by newbthenewbd** [comment]
So, I think now would be a good time to merge this PR, if it hadn't gotten just too crazy :) Gets us close!

**Comment by ronaldtse** [comment]
@newbthenewbd next time could you please rebase the PRs on top of `main`, I've done it this time. Thanks!

**Comment by newbthenewbd** [comment]
OK, sorry :) I'd merged them earlier with the fancy button on github, more commits, more repo, but that will work too

**Comment by ronaldtse** [comment]
No problem. This works great!

**Pull request merged**
