### PR TITLE
Add table export functionality

### LINKED ISSUE #23: Generate table for ISO 2533:1975 Table 5
Screenshot 2024-02-12 at 2 15 03 AM

Screenshot 2024-02-12 at 2 15 20 AM

### LINKED ISSUE #24: Generate table for ISO 2533:1975 Table 6
Screenshot 2024-02-12 at 2 16 19 AM
Screenshot 2024-02-12 at 2 16 35 AM

### LINKED ISSUE #25: Generate table for ISO 2533:1975 Table 7
Screenshot 2024-02-12 at 2 17 04 AM

Screenshot 2024-02-12 at 2 17 23 AM

### LINKED ISSUE #26: Add ISO 2533:1975/ADD 1:1985 calculations
Screenshot 2024-02-12 at 2 19 00 AM
Screenshot 2024-02-12 at 2 19 11 AM
Screenshot 2024-02-12 at 2 19 38 AM
Screenshot 2024-02-12 at 2 19 46 AM

## Table 1
Screenshot 2024-02-12 at 2 20 17 AM

...

Screenshot 2024-02-12 at 2 20 32 AM

## Table 2
Screenshot 2024-02-12 at 2 20 46 AM
...
Screenshot 2024-02-12 at 2 21 11 AM

## Table 3

Screenshot 2024-02-12 at 2 21 24 AM
...
Screenshot 2024-02-12 at 2 21 35 AM

## Table 4
Screenshot 2024-02-12 at 2 21 44 AM
...
Screenshot 2024-02-12 at 2 22 04 AM

## Table 5
Screenshot 2024-02-12 at 2 22 11 AM
...
Screenshot 2024-02-12 at 2 22 27 AM

## Table 6
Screenshot 2024-02-12 at 2 22 48 AM
...
Screenshot 2024-02-12 at 2 23 09 AM

### LINKED ISSUE #27: Add ISO 2533:1975/ADD 2:1997 calculations
Screenshot 2024-02-12 at 2 24 22 AM
Screenshot 2024-02-12 at 2 24 29 AM

## Table 1
Screenshot 2024-02-12 at 2 24 49 AM

Screenshot 2024-02-12 at 2 25 00 AM
...
Screenshot 2024-02-12 at 2 25 38 AM

## Table 2

Screenshot 2024-02-12 at 2 26 01 AM

Screenshot 2024-02-12 at 2 26 11 AM
Screenshot 2024-02-12 at 2 26 43 AM

Screenshot 2024-02-12 at 2 26 29 AM
Screenshot 2024-02-12 at 2 26 49 AM

## Table 3

Screenshot 2024-02-12 at 2 27 41 AM

Screenshot 2024-02-12 at 2 27 48 AM
Screenshot 2024-02-12 at 2 28 14 AM

Screenshot 2024-02-12 at 2 28 00 AM
Screenshot 2024-02-12 at 2 28 23 AM

## Table 4

Screenshot 2024-02-12 at 2 28 35 AM

Screenshot 2024-02-12 at 2 28 47 AM

Screenshot 2024-02-12 at 2 29 22 AM

Screenshot 2024-02-12 at 2 28 57 AM

Screenshot 2024-02-12 at 2 29 16 AM

## Table 5
Screenshot 2024-02-12 at 2 29 55 AM

Screenshot 2024-02-12 at 2 30 09 AM
Screenshot 2024-02-12 at 2 30 32 AM

Screenshot 2024-02-12 at 2 30 16 AM
Screenshot 2024-02-12 at 2 30 42 AM

## Table 6

Screenshot 2024-02-12 at 2 31 31 AM
Screenshot 2024-02-12 at 2 31 39 AM
Screenshot 2024-02-12 at 2 32 05 AM

Screenshot 2024-02-12 at 2 31 50 AM
Screenshot 2024-02-12 at 2 32 16 AM

### PR DESCRIPTION
**Pull request by newbthenewbd**
A simple Ruby application making use of the procedures:
```ruby
require "atmospheric"

Atmospheric::Export.iso_2533_1975_table5_to_yaml("table5.yaml")
Atmospheric::Export.iso_2533_1975_table6_to_yaml("table6.yaml")
Atmospheric::Export.iso_2533_1975_table7_to_yaml("table7.yaml")
```

I attach the resulting tables:
image

:upside_down_face: 

[tables.zip](https://github.com/metanorma/atmospheric/files/14731356/tables.zip)

### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by newbthenewbd** [comment]
Going to add the addendum tables to this PR, too...

**Comment by newbthenewbd** [comment]
A small surprise with the addendum 1 tables: the formulae calculate geopotential altitude as a function of pressure... and their choice depends on geopotential altitude :upside_down_face:

Assuming that the functions are monotonic, I suppose that we first calculate the boundary conditions for pressure, and choose further based on that? Shall do it early Monday morning :face_in_clouds:

As for the happier news, a zipfile including the addendum 2 tables roughly as I figured they should be done follows! :)

[tables.zip](https://github.com/metanorma/atmospheric/files/14733797/tables.zip)

**Comment by newbthenewbd** [comment]
OK, all the tables are here!

Exporting example:
```ruby
require "atmospheric"

Atmospheric::Export.iso_2533_1975_table5_to_yaml("iso-2533-1975-table5.yaml")
Atmospheric::Export.iso_2533_1975_table6_to_yaml("iso-2533-1975-table6.yaml")
Atmospheric::Export.iso_2533_1975_table7_to_yaml("iso-2533-1975-table7.yaml")

Atmospheric::Export.iso_2533_add_1_1985_table1_to_yaml("iso-2533-add-1-1985-table1.yaml")
Atmospheric::Export.iso_2533_add_1_1985_table2_to_yaml("iso-2533-add-1-1985-table2.yaml")
Atmospheric::Export.iso_2533_add_1_1985_table3_to_yaml("iso-2533-add-1-1985-table3.yaml")
Atmospheric::Export.iso_2533_add_1_1985_table4_to_yaml("iso-2533-add-1-1985-table4.yaml")
Atmospheric::Export.iso_2533_add_1_1985_table5_to_yaml("iso-2533-add-1-1985-table5.yaml")
Atmospheric::Export.iso_2533_add_1_1985_table6_to_yaml("iso-2533-add-1-1985-table6.yaml")

Atmospheric::Export.iso_2533_add_2_1997_table1_to_yaml("iso-2533-add-2-1997-table1.yaml")
Atmospheric::Export.iso_2533_add_2_1997_table2_to_yaml("iso-2533-add-2-1997-table2.yaml")
Atmospheric::Export.iso_2533_add_2_1997_table3_to_yaml("iso-2533-add-2-1997-table3.yaml")
Atmospheric::Export.iso_2533_add_2_1997_table4_to_yaml("iso-2533-add-2-1997-table4.yaml")
Atmospheric::Export.iso_2533_add_2_1997_table5_to_yaml("iso-2533-add-2-1997-table5.yaml")
Atmospheric::Export.iso_2533_add_2_1997_table6_to_yaml("iso-2533-add-2-1997-table6.yaml")
```

Generated results:
[tables.zip](https://github.com/metanorma/atmospheric/files/14740292/tables.zip)

Par for the course, small divergences from the original values exist :(

It is also quite a mess to Rubocop, but I believe that a deduplicating refactor that I am potentially thinking of might actually make it less straightforward to read than it currently is - opinions?

**Comment by ronaldtse** [comment]
Merging first. Thanks!

**Pull request merged**
